from setuptools import setup, find_packages

def readme():
    with open('README.rst') as f:
        return f.read()

setup(name='pySlipQt',
      version='0.1.0',
      description='A slipmap widget for PyQt5',
      long_description=readme(),
      url='http://github.com/rzzzwilson/pySlipQt',
      author='Ross Wilson',
      author_email='rzzzwilson@gmail.com',
      license='MIT',
      packages=find_packages(),
      data_files=[('examples', ['examples/README.rst', 'examples/display_text.py',
                                'examples/layer_control.py', 'examples/make_gmt_tiles.py',
                                'examples/numofcpus.py', 'examples/pyslipqt_demo.py',
                                'examples/tkinter_error.py', 'examples/utils.py']),
                  ('examples/graphics', ['examples/graphics/Qt_logo.png',
                                         'examples/graphics/arrow_down.png',
                                         'examples/graphics/arrow_left.png',
                                         'examples/graphics/arrow_leftdown.png',
                                         'examples/graphics/arrow_leftup.png',
                                         'examples/graphics/arrow_right.png',
                                         'examples/graphics/arrow_rightdown.png',
                                         'examples/graphics/arrow_rightup.png',
                                         'examples/graphics/arrow_up.png',
                                         'examples/graphics/compass_rose.png',
                                         'examples/graphics/error_tile.png',
                                         'examples/graphics/img2py.py',
                                         'examples/graphics/pending_image.png',
                                         'examples/graphics/pyslip_demo_gmt.png',
                                         'examples/graphics/pyslip_demo_osm.png',
                                         'examples/graphics/pyslipqt_logo.png',
                                         'examples/graphics/shipwreck.png',])],
      install_requires=['pyqt5', 'python'],
      classifiers=['Development Status :: 3 - Alpha',
                   'Intended Audience :: Developers',
                   'License :: OSI Approved :: MIT License',
                   'Operating System :: OS Independent',
                   'Programming Language :: Python :: 3 :: Only'],
      keywords='python pyqt5 slipmap map',
      download_url='https://github.com/rzzzwilson/pySlipQt/releases/tag/0.1.0',
#      include_package_data=True,
      zip_safe=False)
